### ISSUE TITLE
[Resolved] Unmappable character for UTF8 encoding

### ISSUE THREAD

**Issue by RoughTomato** [inzOprogramowaniaUZ/violetumleditor#13]
`violet-framework/.../workspace/editorpart/behavior/EditSelectedDuplicateBehavior.java` is creating compilation error. 

`[72, 46] error : unmappable character for encoding UTF8`

please assign appropriate person to this issue. I'll provide full stack trace at a later date

Problem :
mvn clean install fails

Desired behavior :
 maven builds software without errors.

**Comment by orchowski** [comment]
After mvn clean install i had only one error at "BallAndSocketNode" and there is missing bracket only.
When i fix it, everything runs great. Issue should be edited
EDIT:
Repaired

**Comment by RoughTomato** [comment]
Ok, thanks. Closing issue.
