### ISSUE TITLE
[Resolved][Bug]Duplicate.

### ISSUE THREAD

**Issue by bartoszsledz** [inzOprogramowaniaUZ/violetumleditor#63]
why not work for lillipop and package nodes? they have name fields too

@orchowski

**Comment by wenaro** [comment]
It does not work too if you copy e.g class node

**Comment by orchowski** [comment]
Jak nie macie co robić to wam znajde inne bugi

**Comment by abizukojc** [comment]
@orchowski Explain, why do you think this issue should be closed.
