### ISSUE TITLE
[Resolved]Frame covers another frame at start

### ISSUE THREAD

**Issue by orchowski** [inzOprogramowaniaUZ/violetumleditor#71]
It's looks like this:
![obraz](https://cloud.githubusercontent.com/assets/17548765/23222785/4e7b9e3c-f929-11e6-8678-b8b11a9ea7c1.png)
for me this should be displayed only one frame at the same frame or this frames should be integrated with each other.

**Comment by regit66** [comment]
I add fix ,if autosave file exist  in welcome window will be add new button , pull #73
